version: 4.0.2
main: me.rockyhawk.commandpanels.CommandPanels
name: CommandPanels
author: RockyHawk
api-version: '1.13'
folia-supported: false
description: Fully Custom GUIs. Make your Server Professional.
softdepend: [PlaceholderAPI, Vault, HeadDatabase, MMOItems, floodgate, Skript]
commands:
   panels:
      description: Main plugin command.
      usage: /panels <command> [arguments]
      aliases: [pa]
permissions:
   commandpanels.default:
      default: true
   commandpanels.command:
      default: true
   commandpanels.command.reload:
      default: op
   commandpanels.command.generate:
      default: op
   commandpanels.command.version:
      default: true
   commandpanels.command.data:
      default: op
   commandpanels.command.open:
      default: op
   commandpanels.command.open.other:
      default: op
   commandpanels.command.help:
      default: true
   commandpanels.command.convert:
      default: true